export const languages = [
	{ label: 'JavaScript', value: 'javascript' },
	{ label: 'TypeScript', value: 'typescript' },
	{ label: 'Python', value: 'python' },
	{ label: 'Java', value: 'java' },
	{ label: 'C#', value: 'csharp' },
	{ label: 'C', value: 'c' },
	{ label: 'C++', value: 'cpp' },
	{ label: 'Go (Golang)', value: 'go' },
	{ label: 'Rust', value: 'rust' },
	{ label: 'Kotlin', value: 'kotlin' },
	{ label: 'Swift', value: 'swift' },
	{ label: 'PHP', value: 'php' },
	{ label: 'Ruby', value: 'ruby' },
	{ label: 'Scala', value: 'scala' },
	{ label: 'Dart', value: 'dart' },
	{ label: 'R', value: 'r' },
	{ label: 'Perl', value: 'perl' },
	{ label: 'Lua', value: 'lua' },
	{ label: 'Haskell', value: 'haskell' },
	{ label: 'Clojure', value: 'clojure' },

	// Web & Frontend
	{ label: 'HTML', value: 'html' },
	{ label: 'CSS', value: 'css' },
	{ label: 'SASS/SCSS', value: 'scss' },
	{ label: 'Less', value: 'less' },
	{ label: 'JSX', value: 'jsx' },
	{ label: 'TSX', value: 'tsx' },
];
